name: prometheus-numa-exporter
base: core22
adopt-info: prometheus-numa-exporter
summary: collects backup results and exports them as metrics
version: 0.1
description: |
  The prometheus-numa-exporter is a snap for collecting metrics
  about the usage of NUMA domains on OpenStack hosts. These results
  are exorted as prometheus metrics.

grade: stable
confinement: strict

apps:
  prometheus-numa-exporter:
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    command: bin/prometheus-numa-exporter
    plugs:
      - libvirt
      - network-bind
      - hardware-observe

parts:
  prometheus-numa-exporter:
    source: .
    plugin: python
    python-requirements: [./requirements.txt]
    build-packages:
      - gcc
      - pkg-config
      - libvirt-dev
    stage-packages:
      - libvirt-clients
