name: prometheus-numa-exporter
base: core22
adopt-info: prometheus-numa-exporter
summary: collects backup results and exports them as metrics
version: 0.1
description: |
  The prometheus-numa-exporter is a snap for collecting metrics
  about the usage of NUMA domains on OpenStack hosts. These results
  are exorted as prometheus metrics.

grade: devel
confinement: strict

plugs:
  etc-nova-nova-conf:
    interface: system-files
    read:
    - /etc/nova/nova.conf

apps:
  prometheus-numa-exporter:
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    command: bin/prometheus-numa-exporter
    plugs:
      - network-bind
      - etc-nova-nova-conf
      - hardware-observe

parts:
  prometheus-numa-exporter:
    source: .
    plugin: python
    python-requirements: [./requirements.txt]
