name: prometheus-numa-exporter
base: core22
adopt-info: prometheus-numa-exporter
summary: collects backup results and exports them as metrics
description: |
  The prometheus-numa-exporter is a snap for collecting metrics
  about the usage of NUMA domains on OpenStack hosts. These results
  are exorted as prometheus metrics.

grade: devel
confinement: strict

apps:
  prometheus-numa-exporter:
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    command: bin/prometheus-numa-exporter
    plugs:
      - network-bind

parts:
  prometheus-numa-exporter:
    source: .
    plugin: python
    python-requirements: [./requirements.txt]
    override-build: |
      craftctl default
      craftctl set version=0.0.1
